apiVersion: v1
kind: Pod
metadata:
  name: web-db-pod
  labels:
    app: web-db-app
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 8080
  - name: postgres-container
    image: postgres:latest
    ports:
    - containerPort: 54320
    env:
    - name: POSTGRES_PASSWORD
      value: mysecretpassword